name: lymphowear_remote_app
description: Lymphowear Remote App
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.6
  lottie: ^1.4.3
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^12.0.2
  flutter_native_timezone: ^2.0.0
  rxdart: ^0.27.5
  timezone: ^0.9.0
  flutter_reactive_ble: ^5.0.2
  permission_handler: ^10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/app_icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf